
trainsmall:
	python .\train.py \
	--traindir D:\cygwin64\home\trule\machine_learning_examples\large_files\fruits-360\Training-Small \
	--validdir D:\cygwin64\home\trule\machine_learning_examples\large_files\fruits-360\Test-Small \
	--epochs 100 --initial_epoch 20 \
	--image_size 50 50 --batch_size 128 \
	--modelprefix data\vgg-fruit-360-small- \
	--horizontal_flip true --vertical_flip true \
	--finetune false 